# Using slim here because we need chromium for puppeteer
#
FROM node:8.11.2-alpine

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    git \
    curl \
    bash \
    musl \
    libressl-dev \
    libc6-compat \
    linux-headers \
    build-base \
    gmp-dev \
    libffi-dev \
    libusb-dev

# Update apk repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-2.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Install chromium
RUN apk -U --no-cache \
	--allow-untrusted add \
    zlib-dev \
    chromium \
    xvfb \
    wait4ports \
    xorg-server \
    dbus \
    ttf-freefont \
    mesa-dri-swrast \
    grep \
    udev

# begin create caching layer
COPY package.json /app/package.json
WORKDIR /app
RUN git init \
  && yarn add require-from-string \
  && PUPPETEER_CHROMIUM_REVISION="64.0.3282.168-r0" yarn \
  && rm -rf .git \
  && rm package.json \
  && rm yarn.lock
# end create caching layer

COPY . /app

RUN ETHEREUM_NETWORK=integration yarn build

# Add Chrome as a user. Without this chrome requires that it be run --without-sandbox
# which jest-puppetter doesn't do by default. So, to keep the sandboxing for the
# running of these tests we gotta add a group and user for chrome
RUN  adduser -D chrome
# Run Chrome non-privileged
USER chrome
CMD ["bash"]
